### ISSUE TITLE
Not really an issue but kinda an issue?

### ISSUE THREAD

**Issue by Findire** [stylemessiah/SQLite3-Universal-Binaries#1]
I was clearing out some modules from my phone wondering what I needed and didn't need and I realized I don't need UniversalSafetyNetFix, MagiskHide_Props_Config or even GPay.SQLite fixer (NFC appears to work fine) 
So with that in mind I was like "Maybe I don't need SQLite3 either" Upon removing it the first thing I noticed was sitting on my devices bootloader unlock warning screen for an abnormally long time followed by seeing the T-Mobile boot animation which I had changed to a different animation in Magisk. Once booted up 4 systems apps I had previously removed with debloater magically returned but didn't actually exist, just their package names and no actual app names or icons and crashed repeatedly.
 I also failed both basicIntegiry and ctsProfile checks... So realizing SQLite3 was the only thing I changed I threw it back on and rebooted, everything is perfect now, saw my intended boot animation, no uninstalled apps magically in my launcher and I pass the safetynet check just fine.
I'm wondering if this is normal behavior and why this is a thing, it seems that I now need this module or everything goes to hell.

**Comment by stylemessiah** [comment]
*GPay SQL Fix module *

There is nothing in the GPay SQL Fix module that runs on every boot,
however, when you uninstall it, it reverts the changes made to
the /data/data/com.google.android.gms/databases/dg.db file (sets the
permissions back to 660) and this is by design - to totally revert to
standard and remove any changes made by the module - which should be the
aim of every module (hint: it isnt)

You can see this happen in the log: /cache/payfixuninstall.log
You can also see what happens when you install it: /cache/payfixfirstrun.log

To recap, when you install the module, it checks for the presence of an
sqlite3 binary hides some google apps in magisk (note this wont work
on later magisks - theres no magiskhide  - i have to update it - reason i
havent is that the module is mostly unneeded these days) and clears
data on some google apps. Upon reboot a service.sh script changes
permissions on the /data/data/com.google.android.gms/databases/dg.db file.

*SQLite3 Universal Binaries module*

Possibly the simplest/dumbest module i have, ALL it does is determine if
you have an sqlite3 binary installed, if you dont, it determines the correct
path to install one to (bin or xbin) and copies one to that path. Thats it.
Theres no script that runs on startup, nothing.

Maybe check what modules are installed in /data/abd/modules (*ls
/data/abd/modules* in a (root) terminal) to see if one is present still
that shouldnt be.

**Comment by Findire** [comment]
> *GPay SQL Fix module * There is nothing in the GPay SQL Fix module that runs on every boot, however, when you uninstall it, it reverts the changes made to the /data/data/com.google.android.gms/databases/dg.db file (sets the permissions back to 660) and this is by design - to totally revert to standard and remove any changes made by the module - which should be the aim of every module (hint: it isnt) You can see this happen in the log: /cache/payfixuninstall.log You can also see what happens when you install it: /cache/payfixfirstrun.log To recap, when you install the module, it checks for the presence of an sqlite3 binary hides some google apps in magisk (note this wont work on later magisks - theres no magiskhide - i have to update it - reason i havent is that the module is mostly unneeded these days) and clears data on some google apps. Upon reboot a service.sh script changes permissions on the /data/data/com.google.android.gms/databases/dg.db file. *SQLite3 Universal Binaries module* Possibly the simplest/dumbest module i have, ALL it does is determine if you have an sqlite3 binary installed, if you dont, it determines the correct path to install one to (bin or xbin) and copies one to that path. Thats it. Theres no script that runs on startup, nothing. Maybe check what modules are installed in /data/abd/modules (*ls /data/abd/modules* in a (root) terminal) to see if one is present still that shouldnt be.
> […](#)

Reading your explanation my only thought was "Well that shouldn't have screwed anything up at all" For the hell of it I decided to remove it again and reboot my device. This time around everything is working fine so I have no idea what happened and I now feel foolish for bringing it up and wasting our time. I'm going to assume some crazy freak event occurred during boot that I can't explain and will probably never know the answer to. I should have rebooted a second time before assuming it was the last magisk module I disabled related. But thank you for getting back to me! It's safe to say this is not an issue and it's unlikely anyone else will face this as it didn't actually appear to be related to these modules in particular.

**Comment by stylemessiah** [comment]
Hehe, ive had those moments where things have gone pear shaped for no
reason and then suddenly; next reboot, fine....

No problem, always happy to try and answer the little mysteries when my
modules are involved :)

Have a great weekend
